<?php
/**
 * Created by PhpStorm.
 * User: yan
 * Date: 18-7-27
 * Time: 上午11:35
 */

namespace App\Admin\Extensions;


use Encore\Admin\Form\Field;

class TestCaseUploader extends Field
{
    // 定义视图
    protected $view = 'admin.testcase_uploader';

    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
